// Generated by https://quicktype.io

export interface LazadaProduct {
  adImpUrl: string;
  adzoneName: string;
  affiliateTagValues: number[];
  algoImageList: any[];
  brandId: number;
  brandName: string;
  campaignId: string;
  canGetLink: boolean;
  categoryId: number;
  clickUrl: string;
  commissionDetailUrl: string;
  commissionType: string;
  currency: string;
  discount: string;
  discountPrice: string;
  earnJumpUrl: string;
  eurl: string;
  formatCommission: string;
  formatDiscountPercent: string;
  formatDiscountPrice: string;
  formatMoneyCanEarn: string;
  formatNcCommission: string;
  formatOriginalPrice: string;
  formatRcCommission: string;
  formatSoldCount: string;
  hasVoucher: boolean;
  httpPdpLink: string;
  imageList: string[];
  imageUrl: string;
  isAd: boolean;
  isCluster: boolean;
  isFreeShipping: boolean;
  isSoldOut: boolean;
  isSpu: boolean;
  itemId: string;
  location: string;
  mmCampaignOffer: boolean;
  offerId: string;
  offerType: string;
  originalCommission: string;
  originalMoneyCanEarn: string;
  originalPrice: string;
  pdpJumpUrl: string;
  pdpLink: string;
  platformCommissionRate: string;
  productImageTags: ProductImageTags;
  rating: string;
  recommend: string;
  reviews: string;
  sales7d: number;
  scm: string;
  sellerCommissionRate: string;
  sellerId: string;
  sellerName: string;
  skuId: string;
  soldCount: number;
  title: string;
  titleTagIcons: TitleTagIcon[];
  tppTraceId: string;
  trackInfo: string;
}

export interface ProductImageTags {
  bottom: Bottom;
}

export interface Bottom {
  imgUrl: string;
  style: Style;
  type: string;
}

export interface Style {
  height: string;
  width: string;
}

export interface TitleTagIcon {
  tagIconHeight: string;
  tagIconUrl: string;
  tagIconWidth: string;
}
